"""models finished

Revision ID: 13bb6861af47
Revises: 4507548842e8
Create Date: 2020-12-16 12:50:27.354185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bb6861af47'
down_revision = '4507548842e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composers',
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('biography', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['composer_id'], ['context_objects.context_id'], ),
    sa.PrimaryKeyConstraint('composer_id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=False))

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=False))

    with op.batch_alter_table('context_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.drop_constraint('context_objects_external_uri_key', type_='unique')
        batch_op.drop_constraint('context_objects_uri_key', type_='unique')
        batch_op.drop_column('external_uri')
        batch_op.drop_column('uri')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('track_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('work_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('subsection_type', sa.String(), nullable=False))
        batch_op.drop_constraint('work_components_subsection_id_fkey', type_='foreignkey')
        batch_op.drop_column('scale')
        batch_op.drop_column('subsection_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subsection_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scale', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('work_components_subsection_id_fkey', 'section_names', ['subsection_id'], ['name_id'])
        batch_op.drop_column('subsection_type')
        batch_op.drop_column('component_type')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('track_number')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('context_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('external_uri', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('context_objects_uri_key', ['uri'])
        batch_op.create_unique_constraint('context_objects_external_uri_key', ['external_uri'])
        batch_op.drop_column('image_url')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    op.drop_table('composers')
    # ### end Alembic commands ###
