"""final model simplification

Revision ID: 41a899346087
Revises: 0aaa1dba2ab2
Create Date: 2020-12-22 10:39:51.142448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a899346087'
down_revision = '0aaa1dba2ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performances',
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('performance_id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'performances', ['performance_id'], ['performance_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('performance_id')

    op.drop_table('performances')
    # ### end Alembic commands ###
