"""fixed nested problem

Revision ID: 4507548842e8
Revises: f924a7cc7956
Create Date: 2020-12-11 18:56:50.371509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4507548842e8'
down_revision = 'f924a7cc7956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsections',
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('number_in_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['works.work_id'], ),
    sa.ForeignKeyConstraint(['subsection_id'], ['context_objects.context_id'], ),
    sa.PrimaryKeyConstraint('subsection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subsections')
    # ### end Alembic commands ###
