"""empty message

Revision ID: 49d3b02d5544
Revises: 949f93816da0
Create Date: 2020-12-23 14:30:39.478848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d3b02d5544'
down_revision = '949f93816da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'composers', ['composer_id'], ['composer_id'])

    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.drop_constraint('composers_artist_id_fkey', type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('composers_artist_id_fkey', 'artists', ['artist_id'], ['artist_id'])

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('composer_id')

    # ### end Alembic commands ###
