"""more data types corrected

Revision ID: 6f9809646b7c
Revises: f9a8fb1a665c
Create Date: 2020-12-18 13:33:48.911583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9809646b7c'
down_revision = 'f9a8fb1a665c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint('artists_external_id_key', type_='unique')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('artists_external_id_key', ['external_id'])

    # ### end Alembic commands ###
