"""track number nullable

Revision ID: 825a043c865a
Revises: 82cda9991dd9
Create Date: 2020-12-17 16:28:10.946507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825a043c865a'
down_revision = '82cda9991dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('track_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('track_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
