"""image url opt

Revision ID: 82cda9991dd9
Revises: 13bb6861af47
Create Date: 2020-12-17 15:33:52.407077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cda9991dd9'
down_revision = '13bb6861af47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['external_id'])

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['external_id'])

    with op.batch_alter_table('context_objects', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['external_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('context_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
