"""artist added

Revision ID: 8671126c7b86
Revises: 
Create Date: 2020-12-11 13:43:12.149338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8671126c7b86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_objects',
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('external_uri', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('context_id'),
    sa.UniqueConstraint('external_uri'),
    sa.UniqueConstraint('uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('context_objects')
    # ### end Alembic commands ###
