"""mtm track artists added

Revision ID: 8985251830d4
Revises: 83852075902c
Create Date: 2020-12-11 15:43:40.543904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8985251830d4'
down_revision = '83852075902c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks_artists',
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks_artists')
    # ### end Alembic commands ###
