"""initial migration

Revision ID: 949f93816da0
Revises: 
Create Date: 2020-12-23 13:05:34.734928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949f93816da0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('album_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('album_type', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_table('artists',
    sa.Column('artist_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('composers',
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('biography', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('composer_id')
    )
    op.create_table('works',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('catalog_no', sa.String(), nullable=True),
    sa.Column('opus_no', sa.String(), nullable=True),
    sa.Column('date_written', sa.Date(), nullable=True),
    sa.Column('more_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.composer_id'], ),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_table('performances',
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('performance_id')
    )
    op.create_table('tracks',
    sa.Column('track_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sanitized_name', sa.String(), nullable=True),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('disc_no', sa.Integer(), nullable=False),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.performance_id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_table('tracks_artists',
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('artist_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks_artists')
    op.drop_table('tracks')
    op.drop_table('performances')
    op.drop_table('works')
    op.drop_table('composers')
    op.drop_table('artists')
    op.drop_table('albums')
    # ### end Alembic commands ###
