"""album added to performance

Revision ID: bf3c6b8855f2
Revises: 41a899346087
Create Date: 2020-12-22 15:18:31.779304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3c6b8855f2'
down_revision = '41a899346087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_id', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'albums', ['album_id'], ['album_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('album_id')

    # ### end Alembic commands ###
