"""work added

Revision ID: da66c1b64bdb
Revises: 8985251830d4
Create Date: 2020-12-11 16:32:38.973104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da66c1b64bdb'
down_revision = '8985251830d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_components',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('scale', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['context_objects.context_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('works',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('date_written', sa.Date(), nullable=False),
    sa.Column('genre', sa.Enum('symphony', 'concerto', 'opera', 'ballet', 'chamber', 'other', name='genre'), nullable=False),
    sa.Column('genre_ordinal', sa.Integer(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('more_info', sa.String(), nullable=True),
    sa.Column('catalog_no', sa.String(), nullable=True),
    sa.Column('opus_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['work_components.component_id'], ),
    sa.PrimaryKeyConstraint('work_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('work_components')
    # ### end Alembic commands ###
