"""work optimization

Revision ID: f924a7cc7956
Revises: da66c1b64bdb
Create Date: 2020-12-11 17:38:08.458433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f924a7cc7956'
down_revision = 'da66c1b64bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_names',
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name_id')
    )
    with op.batch_alter_table('work_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subsection_id', sa.Integer(), nullable=True))
        batch_op.alter_column('scale',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key(None, 'section_names', ['subsection_id'], ['name_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('scale',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('subsection_id')

    op.drop_table('section_names')
    # ### end Alembic commands ###
