"""testing string ids

Revision ID: f9a8fb1a665c
Revises: ee5879c3a9f8
Create Date: 2020-12-18 13:17:01.962540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a8fb1a665c'
down_revision = 'ee5879c3a9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint('albums_external_id_key', type_='unique')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint('tracks_external_id_key', type_='unique')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('tracks_external_id_key', ['external_id'])

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('albums_external_id_key', ['external_id'])

    # ### end Alembic commands ###
