name: Continuous Integration

on:
  push:


jobs:
  test-suite:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        env:
          FLASK_ENV: "testing"
          SHOW_SQL: 1
          ADMIN_TOKEN_FILEPATH: "dev.json"
          REDIRECT_URL: "https://127.0.0.1:5000"
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          ADMIN_REFRESH_TOKEN: ${{ secrets.ADMIN_REFRESH_TOKEN }}

        run: |
          python -m unittest discover test
      - name: Check Type Hinting
        if: ${{ always() }}
        run: |
          mypy -p spotify_opus --ignore-missing-imports
      - name: Check PEP 8 Formatting
        if: ${{ always() }}
        run: |
          flake8 --exclude .git,venv,migrations

